apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: same-namespace2
  namespace: gateway-conformance-infra
spec:
  gatewayClassName: envoy-gateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 8082
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Same
    name: tls
    port: 4432
    protocol: TLS
    tls:
      mode: Passthrough
